language: ruby
rvm:
- 2.1

# install jekyll from gemfile
install:
   - bundle install
   - chmod +x ./scripts/build.sh
   - ./scripts/build.sh

script: true

# branch whitelist, only for GitHub Pages
branches:
  only:
  - build

# deploy to githup pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  on:
    branch: master
